wandb_version: 1

epochs:
  desc: null
  value: 10
lr:
  desc: null
  value: 0.001
patience:
  desc: null
  value: 5
min_delta:
  desc: null
  value: 0
batch_size:
  desc: null
  value: 20
_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.17.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1741097297
    t:
      1:
      - 1
      - 41
      - 55
      - 105
      2:
      - 1
      - 41
      - 55
      - 105
      3:
      - 16
      - 23
      4: 3.12.2
      5: 0.17.3
      8:
      - 2
      - 4
      - 5
      13: darwin-arm64
